### ISSUE TITLE
elm reactor doesn't seem to work for elm 0.19.1

### ISSUE THREAD

**Issue by benkoshy** [wintvelt/elm-html5-drag-drop#1]
Hi there

Thank you for posting your code.

I'm using elm 0.19.1.

I've cloned the repo and have run `elm reactor`

but when I click on the examples it doesn't seem to work:

![tutorial_finished](https://user-images.githubusercontent.com/15097447/73143441-09db9100-40ee-11ea-8a2e-c0303a1da4fd.png)

Any advice would be much appreciated

regards

Ben

**Comment by wintvelt** [comment]
Hi Ben, 
Thanks for reaching out.
I created the example (and this repo) some time ago (in 2017), when Elm was not yet at 0.19.
Since then I have been distracted from Elm, busy with other stuff, so I never got around to upgrading to 0.19.
Upgrade of this repo is not going to happen anytime soon I am afraid.

**Comment by benkoshy** [comment]
ok thank you.
